config/routes.rb
Rails.application.routes.draw do

  get 'service_hours/index'

  get 'service_hours/show'

  get 'service_hours/create'

  get 'diesel_readings/index'

  get 'diesel_readings/show'

  get 'diesel_readings/create'

get "linegraph" => "homes#show"

  get 'accounts/index'

  get 'accounts/show'

  get 'accounts/add'

  get 'accounts/edit'

  resources :bill_tables
  resources :guard_infos    
  resources :quotation_details
  resources :sender_details
  resources :gen_avails
  resources :gen_expenses
  resources :gen_details
  resources :third_party_providers
  resources :taxes
  resources :banks
	resources :transactions
	resources :accounts
	resources :email_addresses
  resources :diesel_readings
	resources :service_hours
  get "tax_report" => "tax_report#index"
  post "tax_report" => "tax_report#index"
  post "mail_report" => "tax_report#mailReport"

  get 'transactions/index'
  get 'transactions/show'
  post 'transactions/add'
  post 'transactions/create'
  root 'welcome#index'
  get  "dashboard"        => "client_details#dashboard"
  post "dashboard"	 => "client_details#dashboard"
  get "profitloss" => "gen_expenses#profit_loss"
  post "profitloss" => "gen_expenses#profit_loss"
  get "client/:id"   => "client#index"
  post "client/:id" => "client#index"
  get "partylist" => "gen_expenses#party_list"
  post "partylist" => "gen_expenses#party_list"
  get "party_providers" => "gen_expenses#party_providers"
  post "party_providers" => "gen_expenses#party_providers"
  post "third_party_providers/:id" => "third_party_providers#show"
  get  "client"           => "client_details#index"
  post "client"		        => "client_details#index"
  get  "clientdetails"    => "client_details#new"
  post "clientdetails"    => "client_details#new"
  get  "quotations/:id"   => "client_details#quotations"
	get  "active_generators" => "client_details#active_generators"

  get "closed/client_details/:id" => "quotation_details#contractClose"
  get "opened/client_details/:id" => "quotation_details#contractOpen"
  post "closed/client_details/:id" => "quotation_details#contractClose"
  post "opened/client_details/:id" => "quotation_details#contractOpen"
  get  "sender"           => "sender_details#index"
  post "sender"		        => "sender_details#index"
  get  "senderdetails"    => "sender_details#new"
  post "senderdetails"    => "sender_details#new"
  get  "generators"       => "gen_details#index"
  get  "gendetails"       => "gen_details#new"
  post "gendetails"       => "gen_details#new"
  get  "genexpenses"      => "gen_expenses#index"
  get  "expenses"         => "gen_expenses#new" 
	post "bill"         => "gen_expenses#get_bill" 
	get	 "bill"         => "gen_expenses#get_bill" 
  post "expenses"         => "gen_expenses#new"  
	get "download" => "gen_expenses#download"
	post "download" => "gen_expenses#download"
	get "profit_loss" => "gen_expenses#profit_loss"
	post "profit_loss" => "gen_expenses#profit_loss"
  get  "quotationviewer"  => "quotation_details#index"
  get  "profitloss"     => "quotation_details#profitloss"
  get  "thirdparty"       => "third_party_providers#index"
  get  "providers"        => "third_party_providers#new"
  post "providers"        => "third_party_providers#new"
  get  "welcomemail"      => "client_details#mail"
  get  "sendpdfmail/:id"  => "quotation_details#mail"  
  get  "sendpdfmailfake/:id"  => "fake_quotations#mail"  
  get  "notice"           => "quotation_details#notice"
  get  "notice"           => "fake_quotations#notice"
  get  "availableGenerators"     => "gen_avails#new"
  post "availableGenerators"     => "gen_avails#new"
  get  "/approved/quotation_details/:id" => "quotation_details#approve"
  post "/approved/quotation_details/:id" => "quotation_details#approve"

  devise_for :users
    as :user do
      get 'login'               => 'devise/sessions#new'
      post 'login'              => 'devise/sessions#create'
      get 'logout'              => 'devise/sessions#destroy'
      get 'register'            => 'devise/registrations#new'
      get 'registered'          => 'devise/registrations#show'
      get 'passwordReset'       => 'devise/passwords#new'
      get 'changePassword'      => 'devise/passwords#edit'  
      get 'resendConfirmation'  => 'devise/confirmations#new'    
    end

  mount Mercury::Engine => '/'

  resources :client_details do
    member { post :clientUpdate }
  end

  resources :fake_quotations do
    member { post :mercury_update}
  end

  namespace :mercury do
    resources :images
  end
 
  get "*path" => "quotation_details#notfound"      

end

app/controllers/bill_tables_controller.rb
class BillTablesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bill_table, only: [:show, :edit, :update, :destroy]

  # GET /bill_tables
  # GET /bill_tables.json
  def index
    @bill_tables = BillTable.all
  end

  # GET /bill_tables/1
  # GET /bill_tables/1.json
  def show
  end

  # GET /bill_tables/new
  def new
    @bill_table = BillTable.new
  end

  # GET /bill_tables/1/edit
  def edit
  end

  # POST /bill_tables
  # POST /bill_tables.json
  def create
    @bill_table = BillTable.new(bill_table_params)

    respond_to do |format|
      if @bill_table.save
        format.html { redirect_to @bill_table, notice: 'Bill table was successfully created.' }
        format.json { render :show, status: :created, location: @bill_table }
      else
        format.html { render :new }
        format.json { render json: @bill_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bill_tables/1
  # PATCH/PUT /bill_tables/1.json
  def update
    respond_to do |format|
      if @bill_table.update(bill_table_params)
        format.html { redirect_to @bill_table, notice: 'Bill table was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill_table }
      else
        format.html { render :edit }
        format.json { render json: @bill_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_tables/1
  # DELETE /bill_tables/1.json
  def destroy
    @bill_table.destroy
    respond_to do |format|
      format.html { redirect_to bill_tables_url, notice: 'Bill table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill_table
      @bill_table = BillTable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_table_params
      params.require(:bill_table).permit(:bill_id, :monthly_rent, :mail_sent, :third_party_payment, :owner_payment)
    end
end

app/helpers/bill_tables_helper.rb
module BillTablesHelper
end

app/views/bill_tables/_form.html.erb
<%= form_for(@bill_table) do |f| %>
  <% if @bill_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill_table.errors.count, "error") %> prohibited this bill_table from being saved:</h2>

      <ul>
      <% @bill_table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bill_id %><br>
    <%= f.number_field :bill_id %>
  </div>
  <div class="field">
    <%= f.label :monthly_rent %><br>
    <%= f.text_field :monthly_rent %>
  </div>
  <div class="field">
    <%= f.label :mail_sent %><br>
    <%= f.text_field :mail_sent %>
  </div>
  <div class="field">
    <%= f.label :third_party_payment %><br>
    <%= f.text_field :third_party_payment %>
  </div>
  <div class="field">
    <%= f.label :owner_payment %><br>
    <%= f.text_field :owner_payment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bill_tables/edit.html.erb
<h1>Editing Bill Table</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill_table %> |
<%= link_to 'Back', bill_tables_path %>

app/views/bill_tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bill Tables</h1>

<table>
  <thead>
    <tr>
      <th>Bill</th>
      <th>Monthly rent</th>
      <th>Mail sent</th>
      <th>Third party payment</th>
      <th>Owner payment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bill_tables.each do |bill_table| %>
      <tr>
        <td><%= bill_table.bill_id %></td>
        <td><%= bill_table.monthly_rent %></td>
        <td><%= bill_table.mail_sent %></td>
        <td><%= bill_table.third_party_payment %></td>
        <td><%= bill_table.owner_payment %></td>
        <td><%= link_to 'Show', bill_table %></td>
        <td><%= link_to 'Edit', edit_bill_table_path(bill_table) %></td>
        <td><%= link_to 'Destroy', bill_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill table', new_bill_table_path %>

app/views/bill_tables/new.html.erb
<h1>New Bill Table</h1>

<%= render 'form' %>

<%= link_to 'Back', bill_tables_path %>

app/views/bill_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bill:</strong>
  <%= @bill_table.bill_id %>
</p>

<p>
  <strong>Monthly rent:</strong>
  <%= @bill_table.monthly_rent %>
</p>

<p>
  <strong>Mail sent:</strong>
  <%= @bill_table.mail_sent %>
</p>

<p>
  <strong>Third party payment:</strong>
  <%= @bill_table.third_party_payment %>
</p>

<p>
  <strong>Owner payment:</strong>
  <%= @bill_table.owner_payment %>
</p>

<%= link_to 'Edit', edit_bill_table_path(@bill_table) %> |
<%= link_to 'Back', bill_tables_path %>