config/routes.rb
Rails.application.routes.draw do

  get 'service_hours/index'

  get 'service_hours/show'

  get 'service_hours/create'

  get 'diesel_readings/index'

  get 'diesel_readings/show'

  get 'diesel_readings/create'

get "linegraph" => "homes#show"

  get 'accounts/index'

  get 'accounts/show'

  get 'accounts/add'

  get 'accounts/edit'

  resources :bill_tables
  resources :guard_infos    
  resources :quotation_details
  resources :sender_details
  resources :gen_avails
  resources :gen_expenses
  resources :gen_details
  resources :third_party_providers
  resources :taxes
  resources :banks
	resources :transactions
	resources :accounts
	resources :email_addresses
  resources :diesel_readings
	resources :service_hours
  get "tax_report" => "tax_report#index"
  post "tax_report" => "tax_report#index"
  post "mail_report" => "tax_report#mailReport"

  get 'transactions/index'
  get 'transactions/show'
  post 'transactions/add'
  post 'transactions/create'
  root 'welcome#index'
  get  "dashboard"        => "client_details#dashboard"
  post "dashboard"	 => "client_details#dashboard"
  get "profitloss" => "gen_expenses#profit_loss"
  post "profitloss" => "gen_expenses#profit_loss"
  get "client/:id"   => "client#index"
  post "client/:id" => "client#index"
  get "partylist" => "gen_expenses#party_list"
  post "partylist" => "gen_expenses#party_list"
  get "party_providers" => "gen_expenses#party_providers"
  post "party_providers" => "gen_expenses#party_providers"
  post "third_party_providers/:id" => "third_party_providers#show"
  get  "client"           => "client_details#index"
  post "client"		        => "client_details#index"
  get  "clientdetails"    => "client_details#new"
  post "clientdetails"    => "client_details#new"
  get  "quotations/:id"   => "client_details#quotations"
	get  "active_generators" => "client_details#active_generators"

  get "closed/client_details/:id" => "quotation_details#contractClose"
  get "opened/client_details/:id" => "quotation_details#contractOpen"
  post "closed/client_details/:id" => "quotation_details#contractClose"
  post "opened/client_details/:id" => "quotation_details#contractOpen"
  get  "sender"           => "sender_details#index"
  post "sender"		        => "sender_details#index"
  get  "senderdetails"    => "sender_details#new"
  post "senderdetails"    => "sender_details#new"
  get  "generators"       => "gen_details#index"
  get  "gendetails"       => "gen_details#new"
  post "gendetails"       => "gen_details#new"
  get  "genexpenses"      => "gen_expenses#index"
  get  "expenses"         => "gen_expenses#new" 
	post "bill"         => "gen_expenses#get_bill" 
	get	 "bill"         => "gen_expenses#get_bill" 
  post "expenses"         => "gen_expenses#new"  
	get "download" => "gen_expenses#download"
	post "download" => "gen_expenses#download"
	get "profit_loss" => "gen_expenses#profit_loss"
	post "profit_loss" => "gen_expenses#profit_loss"
  get  "quotationviewer"  => "quotation_details#index"
  get  "profitloss"     => "quotation_details#profitloss"
  get  "thirdparty"       => "third_party_providers#index"
  get  "providers"        => "third_party_providers#new"
  post "providers"        => "third_party_providers#new"
  get  "welcomemail"      => "client_details#mail"
  get  "sendpdfmail/:id"  => "quotation_details#mail"  
  get  "sendpdfmailfake/:id"  => "fake_quotations#mail"  
  get  "notice"           => "quotation_details#notice"
  get  "notice"           => "fake_quotations#notice"
  get  "availableGenerators"     => "gen_avails#new"
  post "availableGenerators"     => "gen_avails#new"
  get  "/approved/quotation_details/:id" => "quotation_details#approve"
  post "/approved/quotation_details/:id" => "quotation_details#approve"

  devise_for :users
    as :user do
      get 'login'               => 'devise/sessions#new'
      post 'login'              => 'devise/sessions#create'
      get 'logout'              => 'devise/sessions#destroy'
      get 'register'            => 'devise/registrations#new'
      get 'registered'          => 'devise/registrations#show'
      get 'passwordReset'       => 'devise/passwords#new'
      get 'changePassword'      => 'devise/passwords#edit'  
      get 'resendConfirmation'  => 'devise/confirmations#new'    
    end

  mount Mercury::Engine => '/'

  resources :client_details do
    member { post :clientUpdate }
  end

  resources :fake_quotations do
    member { post :mercury_update}
  end

  namespace :mercury do
    resources :images
  end
 
  get "*path" => "quotation_details#notfound"      

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/bank.rb
class Bank < ActiveRecord::Base
  belongs_to :client_detail
end

app/models/bill_table.rb
class BillTable < ActiveRecord::Base
  belongs_to :quotation
  
  def self.to_csv
    CSV.generate do |csv|
      csv << ["bill_no", "calc_stax", "calc_surcharge", "calc_tds", "Bill Date"]
      all.each do |bill|
				csv << [bill.bill_no, bill.calc_stax, bill.calc_surcharge, bill.calc_tds, bill.created_at.to_formatted_s(:long_ordinal)]
      end
    end
  end
end

app/models/client_detail.rb
class ClientDetail < ActiveRecord::Base
  belongs_to :sender_detail
  has_many :quotation
  has_many :bank

  
  validates_presence_of :contactNo
  validates_format_of :contactNo, with: /[0-9]/
  validates_length_of :contactNo, :maximum =>12, :minimum => 4

  validates_presence_of :sender_details_id
#	validates_presence_of :bank_id
	validates_presence_of :account_id
end

app/models/client_gen_set.rb
class ClientGenSet < ActiveRecord::Base
  belongs_to :quotation_detail
  belongs_to :client_detail
  belongs_to :gen_avail
  belongs_to :gaurd_detail
  belongs_to :third_party_gen
end

app/models/diesel_reading.rb
class DieselReading < ActiveRecord::Base
  belongs_to :client_gen_set
end

app/models/email_addresse.rb
class EmailAddresse < ActiveRecord::Base
end

app/models/fake_quotation.rb
class FakeQuotation < ActiveRecord::Base
  belongs_to :client_details
  belongs_to :sender_details

  protokoll :referenceNumber, :pattern => "AEQF%y###"  
end

app/models/gaurd_detail.rb
class GaurdDetail < ActiveRecord::Base
end

app/models/gen_avail.rb
class GenAvail < ActiveRecord::Base

  validates_presence_of :gen_detail_id
	validates_presence_of :service_due_after
  belongs_to :gen_detail
  protokoll :genID, :pattern => "G%y###"

end

app/models/gen_detail.rb
class GenDetail < ActiveRecord::Base
  
  validates_format_of :genRent, with: /[0-9]/, :message => "accepts Numbers only"
  validates_format_of :total_gen, with: /[0-9]/, :message => "accepts Numbers only"

  has_many :gen_avails	
  has_many :third_party_gens
end

app/models/gen_expense.rb
class GenExpense < ActiveRecord::Base
  belongs_to :client_detail
  
  validates_presence_of :readingBy
end

app/models/quotation_rent.rb
class QuotationRent < ActiveRecord::Base
  belongs_to :client_detail
  belongs_to :quotation_detail
end

app/models/sender_detail.rb
class SenderDetail < ActiveRecord::Base
  has_attached_file :signature, :styles => { :small => "150x150>", med: "200x200", large: "300x300"},
                    :url  => "/assets/sender_signature/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/sender_signature/:id/:style/:basename.:extension"
  validates_attachment_presence :signature
  validates_attachment :signature, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

 
  validates_presence_of :contactNo
  validates_format_of :contactNo, with: /[0-9]/
  validates_length_of :contactNo, :maximum =>12, :minimum => 4

  validates_presence_of :quotationType
end

app/models/service_hour.rb
class ServiceHour < ActiveRecord::Base
	belongs_to :client_gen_set
end

app/models/tax.rb
class Tax < ActiveRecord::Base
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
   def index
   end

   def mail
      QtMailer.qt_email().deliver	
   end
	
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_fakeQuotationHeader.html.erb
<header class="quotationHeader" id="quotationHeader" role="banner" style="display: block;">
    <nav class="navbar", role="navigation">
        <ul class="unlist1" >
            <li ><%= link_to "Home", root_path %></li>        
            <li ><%= link_to "DashBoard", dashboard_path %></li>
            <li><%= link_to "Edit Page", "/editor" + request.path, 
            {:id => "edit_link"} %></li>
            <li><%= link_to "Send Mail", "/sendpdfmailfake/" + 
                @fake_quotation.id.to_s, {:id => "send_mail", 
                    :onclick => "loader();"} %></li>            
            <li><%= link_to 'PDF', fake_quotation_path(@fake_quotation, format: 'pdf')%></li>
        </ul>
    </nav>  
</header>

<script type="text/javascript">
    function loader(){
        $('.preloader').css("display","block");   
    }
</script>        

app/views/welcome/_header.html.erb
<div id="navbar"
  <nav class="navbar navbar-default navbar-static-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-1">
                <ul class="nav navbar-nav navbar-left">
					<li> <%= link_to root_path do %>  Home <% end %> </li>
					<% if user_signed_in? %>
                    <li> <%= link_to dashboard_path do %> Dashboard  <% end %> </li>
                    <li> <%= link_to profitloss_path do %> Profit Loss Sheet <% end %> </li>
					<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Third Party<b class="caret"></b></a>
						<ul class="dropdown-menu">
						<li><%= link_to party_providers_path do%> Providers <% end %></li>
							<li><%= link_to partylist_path do %>Bill <% end %></li>
						</ul>
					</li>
					<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">More<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to active_generators_path do%>Active generators<% end %></li>
							<li><%= link_to tax_report_path do%>Tax reports<% end %></li>
							<li><%= link_to banks_path do %> Add/Edit Banks <% end %> </li>
						</ul>
					</li>

		            <% else %>
        	        <li><%= link_to "Login", login_path %></li>
       		        <% end %>
				</ul>
				<% if user_signed_in? %> 
				<ul class="nav navbar-nav navbar-right">
                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li> <%= link_to accounts_path do %> My Bank accounts <% end %> </li>
                            <li>  <%= link_to email_addresses_path do %> My Email addresses <% end %> </li>
                            <li>  <%= link_to taxes_path do %> Taxes <% end %> </li>
						<!--	<li class="dropdown dropdown-submenu"><a href="#" class="dropdown-toggle" data-toggle="dropdown"> Reports</a>
								<ul class="dropdown-menu">
									<li><a href="#">Client</a></li>
									<li><a href="#">Third Party</a></li>
									<li><a href="#">Taxes</a></li>-->
						</ul>
					</li>
					<li ><%= link_to logout_path do %> Log Out <% end %></li>   
				</ul>
			<% else %>
				<% end %>
            </div><!-- /.navbar-collapse -->
        </nav>
</div>


    

<% if false %>
<header class="header" id="header" role="banner" style="display: block;">
    <nav class="navbar" role="navigation">
        <ul class="unlist1">	
        <%= link_to root_path do %>
                <li >Home</li>	
        <% end %>
        <%= link_to dashboard_path do %>
                <li >Dashboard</li>
        <% end %>
	<%= link_to profitloss_path do %>
                <li >Profit Loss Sheet</li>
        <% end %>
	<%= link_to partylist_path do %>
                <li >Third Party Details</li>
        <% end %>
	<%= link_to accounts_path do %>
                <li >My Bank Accounts</li>
        <% end %>
        <%= link_to email_addresses_path do %>
                <li >Email Addresses</li>
        <% end %>
	 <% if user_signed_in? %>
        <%= link_to logout_path do %>
                <li> Log Out</li>
        <% end %>
            <% else %>       
                <li><%= link_to "Login", login_path %></li>
            <% end %>
        </ul>
    </nav>  
</header>
<% end %>

app/views/welcome/_quotationHeader.html.erb
<header class="quotationHeader" id="quotationHeader" role="banner" style="display: block;">
    <nav class="navbar", role="navigation">
        <ul class="unlist1" >
            <li ><%= link_to "Home", root_path %></li>
			<li ><%= link_to "DashBoard", dashboard_path %></li>
			<% if not @quotation_detail.mailStatus %>
				<li><%= link_to "Edit Page", "/editor" + request.path, {:id => "edit_link"} %></li>
			<% end %>
            <li><%= link_to "Send Mail", "/sendpdfmail/" + @quotation_detail.id.to_s, {:id => "send_mail", :onclick => "loader();"} %></li>
            <li><%= link_to 'PDF', quotation_detail_path(@quotation_detail, format: 'pdf')%></li>
        </ul>
    </nav>  
</header>

<script type="text/javascript">
function loader(){
	$('.preloader').css("display","block");		
}
</script>

app/views/welcome/index.html.erb
<section class="landingPage">    
    <div class="content">
        <div class="box">
            <div class="main-heading" id="main-heading">Welcome to</div>
            <!--%= #image_tag("amrit_logo.png", :class => "amrit-logo", :alt => "amrit engineers logo") %-->
            <div class="amrit" >Rental Business Management System</div> 
            <div class="eng" >Smarter way to control your business</div> 
            <p style="text-align: center;"><a href="/login"><button class="enter">Proceed to Dashboard</button></a></p>
        </div>
    </div>
</section>

app/views/welcome/mail.html.erb
<h1>your email has been sent!</h1>